export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GOOGLELOGIN_SUCCESS = "GOOGLELOGIN_SUCCESS";
export const GOOGLELOGIN_FAIL = "GOOGLELOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";

export const FORGOTPASS_SUCCESS = "FORGOTPASS_SUCCESS";
export const FORGOTPASS_FAIL = "FORGOTPASS_FAIL";

export const RESETPASSTOKENCHECK_SUCCESS = "RESETPASSTOKENCHECK_SUCCESS";
export const RESETPASSTOKENCHECK_FAIL = "RESETPASSTOKENCHECK_FAIL";

export const RESETPASS_SUCCESS = "RESETPASS_SUCCESS";
export const RESETPASS_FAIL = "RESETPASS_FAIL";


export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
